project:
  type: website
  output-dir: docs

website:
  title: "Jiafang Song"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: education.qmd
        text: Education
