project:
  type: website
  output-dir: docs

website:
  title: "Jiafang Song"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - projects.qmd
    right:
      - icon: github
        href: https://github.com/jfsong100
        aria-label: GitHub
      - icon: mortarboard   
        href: https://scholar.google.com/citations?user=HDx3_aYAAAAJ&hl=en&authuser=1
        aria-label: Google Scholar
      - icon: linkedin
        href: https://www.linkedin.com/in/jiafang-song-bb7464188/
        aria-label: LinkedIn
